server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  # Docker container logs (for your services: postgres, mongo, redis, etc.)
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/log/containers/*.log

  # Ember service logs
  - job_name: nestjs-local
    static_configs:
      - targets:
          - localhost
        labels:
          job: nestjs
          service: ember
          __path__: /var/log/nestjs/*.log
