server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'

  # NestJS application logs (via stdout/stderr)
  - job_name: nestjs-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nestjs
          service: ember
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            output: log
            container_id: attrs.tag
      - regex:
          expression: '^(?P<time>\S+) (?P<stream>stdout|stderr) \S+ (?P<content>.*)$'
          source: output
      - timestamp:
          format: RFC3339Nano
          source: time
      - output:
          source: content
