global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # NestJS application metrics (when you add /metrics endpoint)
  - job_name: 'nestjs-ember'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Docker containers metrics (if you enable)
  - job_name: 'docker-containers'
    static_configs:
      - targets: ['host.docker.internal:9323']

remote_write:
  - url: http://mimir:9009/api/v1/push
